function y = get_measurement_value(x)
    y = [(atan2((x(5)-x(2)), (x(4)-x(1)))-x(3)), ...
         sqrt((x(1)-x(4)).^2+(x(2)-x(5)).^2), ...
         (atan2((x(2)-x(5)), (x(1)-x(4)))-x(6)), ...
         x(4), ...
         x(5)]';
end